version: '3.1'

services:
  mongo:
    build:
        context: ./db
        dockerfile: Dockerfile
    #image: yooml/mongo-hudex-dev:v3
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - mynetwork
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

volumes:
  mongodata:

networks:
  mynetwork:
